"use client";

import { useMemo } from "react";

/**
 * =========================================================
 * MASCOT ENGINE v2
 * Module: MascotAnimationController
 * Responsibility:
 * Applies the final transform generated by the render
 * pipeline to the mascot container.
 *
 * For now this controller only provides a stable wrapper.
 * Future layers (Breathing, Idle, Blink, Physics, etc.)
 * will inject their transforms here.
 * =========================================================
 */

export default function MascotAnimationController({
  children,
  style = {},
  className = "",
}) {
  const mergedStyle = useMemo(
    () => ({
      transformOrigin: "center center",
      willChange: "transform",
      ...style,
    }),
    [style]
  );

  return (
    <div
      style={mergedStyle}
      className={`inline-flex items-center justify-center ${className}`}
    >
      {children}
    </div>
  );
}