export const TUTORIAL_CATEGORIES = [
  {
    id: "compras",
    label: "Compras",
    icon: "🛒",
    description: "Cómo comprar productos",
    color: "from-green-400 to-emerald-500",
  },
  {
    id: "ventas",
    label: "Ventas",
    icon: "🏪",
    description: "Cómo vender en la plataforma",
    color: "from-blue-400 to-cyan-500",
  },
  {
    id: "pagos",
    label: "Pagos",
    icon: "💳",
    description: "Métodos de pago disponibles",
    color: "from-purple-400 to-violet-500",
  },
  {
    id: "dashboard",
    label: "Dashboard",
    icon: "📊",
    description: "Panel de control del vendedor",
    color: "from-orange-400 to-amber-500",
  },
  {
    id: "cuenta",
    label: "Mi Cuenta",
    icon: "👤",
    description: "Configuración y perfil",
    color: "from-pink-400 to-rose-500",
  },
  {
    id: "mascotas",
    label: "Mascotas",
    icon: "🐾",
    description: "Sistema de mascotas y monedas",
    color: "from-yellow-400 to-amber-500",
  },
  {
    id: "ofertas",
    label: "Ofertas",
    icon: "🔥",
    description: "Descuentos y promociones",
    color: "from-red-400 to-orange-500",
  },
  {
    id: "envios",
    label: "Envíos",
    icon: "📦",
    description: "Política de envío y seguimiento",
    color: "from-teal-400 to-cyan-500",
  },
];

export const TUTORIALS = {
  compras: [
    {
      id: "comprar-pasos",
      title: "Cómo comprar un producto",
      icon: "🛒",
      steps: [
        { text: "Busca el producto que deseas en la barra de búsqueda o explora las categorías", illustration: "searchbar" },
        { text: "Haz clic en el producto para ver detalles, fotos, precio y descripción", illustration: "productCard" },
        { text: "Haz clic en 'Agregar al carrito' o 'Comprar ahora'", illustration: "cart" },
        { text: "Revisa tu carrito (ícono 🛒 arriba a la derecha)", illustration: "cart" },
        { text: "Haz clic en 'Ir al checkout' para confirmar tu compra", illustration: "checkout" },
        { text: "Elige tu método de pago: Yape, Plin, transferencia bancaria o tarjeta", illustration: "checkout" },
        { text: "Confirma el pedido y ¡listo! Recibirás un correo de confirmación", illustration: "notifications" },
      ],
      tip: "Puedes agregar productos de diferentes tiendas en un solo pedido.",
      url: "/",
      urlLabel: "Ir a la tienda",
    },
    {
      id: "agregar-carrito",
      title: "Agregar productos al carrito",
      icon: "🛒",
      steps: [
        { text: "Encuentra el producto que te gusta", illustration: "search" },
        { text: "Haz clic en 'Ver detalle' para abrir la página del producto", illustration: "productCard" },
        { text: "Selecciona la cantidad que deseas", illustration: "productCard" },
        { text: "Haz clic en el botón 'Agregar al carrito'", illustration: "cart" },
        { text: "El producto se añadirá a tu carrito (verás el contador incrementarse)", illustration: "cart" },
        { text: "Puedes seguir comprando o ir al carrito", illustration: "scroll" },
      ],
      tip: "El carrito guarda tus productos aunque cierres el navegador.",
      url: "/",
      urlLabel: "Ver productos",
    },
    {
      id: "checkout-pago",
      title: "Proceso de pago (Checkout)",
      icon: "💳",
      steps: [
        { text: "Ve a tu carrito y haz clic en 'Ir al checkout'", illustration: "cart" },
        { text: "Revisa los productos y el total a pagar", illustration: "checkout" },
        { text: "Ingresa tu dirección de envío", illustration: "checkout" },
        { text: "Selecciona el método de pago preferido", illustration: "checkout" },
        { text: "Si eliges Yape/Plin: envía el comprobante al vendedor", illustration: "yape" },
        { text: "Si eliges transferencia: realiza el depósito y sube el comprobante", illustration: "transfer" },
        { text: "Si eliges tarjeta: ingresa los datos de tu tarjeta de forma segura", illustration: "checkout" },
        { text: "Confirma el pedido — ¡recibirás un email de confirmación!", illustration: "notifications" },
      ],
      tip: "Los pagos con Yape se confirman en minutos.",
      url: "/",
      urlLabel: "Ver productos",
    },
    {
      id: "seguir-pedido",
      title: "Seguir mi pedido",
      icon: "📦",
      steps: [
        { text: "Inicia sesión en tu cuenta", illustration: "profile" },
        { text: "Ve a 'Mi cuenta' → 'Mis pedidos'", illustration: "orders" },
        { text: "Selecciona el pedido que quieres rastrear", illustration: "orders" },
        { text: "Verás el estado actual: Pendiente / Procesando / Enviado / Entregado", illustration: "orders" },
        { text: "Si está enviado, verás el número de guía y transportista", illustration: "orders" },
        { text: "Haz clic en 'Seguimiento' para ver la ubicación en tiempo real", illustration: "notifications" },
      ],
      tip: "También recibirás actualizaciones por email y WhatsApp.",
      url: "/",
      urlLabel: "Ir a mi cuenta",
    },
  ],
  ventas: [
    {
      id: "crear-tienda",
      title: "Crear mi tienda",
      icon: "🏪",
      steps: [
        { text: "Regístrate gratuitamente con tu email", illustration: "profile" },
        { text: "Inicia sesión en tu cuenta", illustration: "profile" },
        { text: "Ve a tu Dashboard (menú usuario → Dashboard)", illustration: "dashboard" },
        { text: "Haz clic en 'Configurar mi tienda'", illustration: "store" },
        { text: "Ingresa el nombre de tu tienda", illustration: "store" },
        { text: "Escribe una descripción atractiva", illustration: "store" },
        { text: "Sube tu logo y banner", illustration: "upload" },
        { text: "¡Tu tienda está lista para vender!", illustration: "store" },
      ],
      tip: "Las tiendas con logo y descripción completa venden 3 veces más.",
      url: "/dashboard",
      urlLabel: "Ir al Dashboard",
    },
    {
      id: "agregar-producto",
      title: "Agregar un producto",
      icon: "📦",
      steps: [
        { text: "Ve a Dashboard → Productos", illustration: "dashboard" },
        { text: "Haz clic en 'Nuevo Producto'", illustration: "productForm" },
        { text: "Sube las fotos del producto (arrastra o selecciona)", illustration: "upload" },
        { text: "Escribe el nombre del producto (claro y descriptivo)", illustration: "productForm" },
        { text: "Describe el producto con detalles: materiales, tamaño, uso", illustration: "productForm" },
        { text: "Ingresa el precio en soles (S/)", illustration: "productForm" },
        { text: "Selecciona la categoría", illustration: "categories" },
        { text: "Agrega stock disponible", illustration: "productForm" },
        { text: "Haz clic en 'Guardar' — ¡tu producto está publicado!", illustration: "productForm" },
      ],
      tip: "Usa fotos con fondo blanco y buena iluminación para mejor presentación.",
      url: "/dashboard/products",
      urlLabel: "Mis productos",
    },
    {
      id: "gestionar-pedidos",
      title: "Gestionar pedidos",
      icon: "🧾",
      steps: [
        { text: "Ve a Dashboard → Órdenes", illustration: "dashboard" },
        { text: "Verás todos los pedidos recibidos con su estado", illustration: "orders" },
        { text: "Haz clic en un pedido para ver detalles", illustration: "orders" },
        { text: "Cambia el estado según el progreso:", illustration: "orders" },
        { text: "  • Pendiente → Procesando (cuando empieces a preparar)", illustration: "orders" },
        { text: "  • Procesando → Enviado (cuando lo envíes)", illustration: "orders" },
        { text: "  • Enviado → Entregado (cuando el cliente reciba)", illustration: "orders" },
        { text: "Confirma el pago recibido del cliente", illustration: "notifications" },
      ],
      tip: "Responde rápido a los clientes para mejorar tu reputación y ventas.",
      url: "/dashboard/orders",
      urlLabel: "Ver órdenes",
    },
    {
      id: "estadisticas",
      title: "Ver mis estadísticas",
      icon: "📊",
      steps: [
        { text: "Ve a Dashboard → Inicio", illustration: "dashboard" },
        { text: "En la parte superior verás las métricas principales:", illustration: "dashboard" },
        { text: "  • Productos publicados", illustration: "dashboard" },
        { text: "  • Pedidos totales", illustration: "dashboard" },
        { text: "  • Ingresos acumulados", illustration: "dashboard" },
        { text: "  • Visitas a tu tienda", illustration: "dashboard" },
        { text: "Desplázate hacia abajo para ver gráficos de tendencia", illustration: "dashboard" },
        { text: "Filtra por período: 7 días, 30 días, último trimestre", illustration: "dashboard" },
      ],
      tip: "Revisa tus estadísticas semanalmente para identificar productos más vendidos.",
      url: "/dashboard",
      urlLabel: "Ver Dashboard",
    },
  ],
  pagos: [
    {
      id: "metodos-pago",
      title: "Métodos de pago disponibles",
      icon: "💳",
      steps: [
        { text: "🟣 Yape — Pago instantáneo por celular. Solo envía el comprobante al vendedor.", illustration: "yape" },
        { text: "🔵 Plin — Transferencia rápida entre bancos. Se confirma en minutos.", illustration: "yape" },
        { text: "🏦 Transferencia bancaria — CCI o cuenta directa (BCP, Interbank, etc.)", illustration: "transfer" },
        { text: "💳 Tarjeta de crédito/débito — Vía Culqi (100% seguro y encriptado)", illustration: "checkout" },
        { text: "💵 PagoEfectivo — Paga en efectivo en tiendas autorizadas", illustration: "checkout" },
      ],
      tip: "Yape y Plin son los métodos más rápidos para confirmar tu pedido.",
      url: "/",
      urlLabel: "Ir a comprar",
    },
    {
      id: "pagar-con-yape",
      title: "Pagar con Yape",
      icon: "📱",
      steps: [
        { text: "Selecciona Yape como método de pago en el checkout", illustration: "checkout" },
        { text: "Copia el número de celular del vendedor (aparece en pantalla)", illustration: "yape" },
        { text: "Abre tu app Yape en tu celular", illustration: "yape" },
        { text: "Envía el monto exacto al número indicado", illustration: "yape" },
        { text: "Toma captura de pantalla del comprobante", illustration: "yape" },
        { text: "Sube la captura en el formulario de confirmación", illustration: "upload" },
        { text: "Haz clic en 'Confirmar pago' — ¡listo!", illustration: "notifications" },
      ],
      tip: "El pago se confirma automáticamente en pocos minutos.",
      url: "/",
      urlLabel: "Ir a comprar",
    },
  ],
  dashboard: [
    {
      id: "panel-control",
      title: "Panel de control (Dashboard)",
      icon: "📊",
      steps: [
        { text: "Haz clic en tu avatar → 'Dashboard'", illustration: "profile" },
        { text: "Verás las tarjetas de acceso rápido:", illustration: "dashboard" },
        { text: "  • 📦 Productos — Gestionar tu catálogo", illustration: "dashboard" },
        { text: "  • 🧾 Órdenes — Ver y gestionar pedidos", illustration: "dashboard" },
        { text: "  • 📊 Estadísticas — Métricas de ventas", illustration: "dashboard" },
        { text: "  • ⚙️ Configurar — Ajustes de tu tienda", illustration: "dashboard" },
        { text: "Haz clic en cualquier tarjeta para acceder", illustration: "dashboard" },
      ],
      tip: "El dashboard se adapta a tu plan (Free o Full).",
      url: "/dashboard",
      urlLabel: "Abrir Dashboard",
    },
    {
      id: "configurar-tienda",
      title: "Configurar mi tienda",
      icon: "⚙️",
      steps: [
        { text: "Ve a Dashboard → Configurar", illustration: "dashboard" },
        { text: "Edita el nombre de tu tienda", illustration: "store" },
        { text: "Escribe una descripción atractiva para tus clientes", illustration: "store" },
        { text: "Sube tu logo (cuadrado, mínimo 200x200px)", illustration: "upload" },
        { text: "Sube un banner para la cabecera de tu tienda", illustration: "upload" },
        { text: "Configura tus datos de contacto", illustration: "store" },
        { text: "Guarda los cambios — ¡tu tienda se actualiza al instante!", illustration: "store" },
      ],
      tip: "Un logo profesional genera confianza en los compradores.",
      url: "/dashboard",
      urlLabel: "Configurar tienda",
    },
  ],
  cuenta: [
    {
      id: "editar-perfil",
      title: "Editar mi perfil",
      icon: "👤",
      steps: [
        { text: "Haz clic en tu avatar → 'Mi cuenta'", illustration: "profile" },
        { text: "Haz clic en 'Editar perfil'", illustration: "profile" },
        { text: "Actualiza tu nombre completo", illustration: "profile" },
        { text: "Agrega o cambia tu número de teléfono", illustration: "profile" },
        { text: "Sube una foto de perfil", illustration: "upload" },
        { text: "Guarda los cambios", illustration: "profile" },
      ],
      tip: "Un perfil completo genera más confianza en los compradores.",
      url: "/dashboard/profile/edit",
      urlLabel: "Editar perfil",
    },
    {
      id: "cambiar-contrasena",
      title: "Cambiar contraseña",
      icon: "🔒",
      steps: [
        { text: "Ve a Mi cuenta → Configuración", illustration: "profile" },
        { text: "Haz clic en 'Seguridad'", illustration: "profile" },
        { text: "Ingresa tu contraseña actual", illustration: "profile" },
        { text: "Escribe la nueva contraseña (mínimo 6 caracteres)", illustration: "profile" },
        { text: "Confirma la nueva contraseña", illustration: "profile" },
        { text: "Haz clic en 'Guardar'", illustration: "notifications" },
      ],
      tip: "Usa una contraseña segura con letras, números y símbolos.",
      url: "/dashboard/profile/edit",
      urlLabel: "Configurar cuenta",
    },
    {
      id: "plan-full",
      title: "Actualizar a Plan Full",
      icon: "⬆️",
      steps: [
        { text: "Ve a Dashboard → Planes o haz clic en 'Upgrade'", illustration: "upgrade" },
        { text: "Revisa las ventajas del Plan Full:", illustration: "upgrade" },
        { text: "  • Vender sin límites de productos", illustration: "upgrade" },
        { text: "  • Herramientas de análisis avanzadas", illustration: "upgrade" },
        { text: "  • Soporte prioritario", illustration: "upgrade" },
        { text: "  • Mayor visibilidad en búsquedas", illustration: "upgrade" },
        { text: "Elige método de pago: Yape, transferencia o tarjeta", illustration: "yape" },
        { text: "Realiza el pago de S/ 199/año", illustration: "transfer" },
        { text: "¡Tu cuenta se actualiza automáticamente!", illustration: "notifications" },
      ],
      tip: "El Plan Full cuesta solo S/ 199/año (S/ 16.58/mes).",
      url: "/upgrade",
      urlLabel: "Ver Planes",
    },
  ],
  mascotas: [
    {
      id: "mascota-basico",
      title: "Cómo usar tu mascota",
      icon: "🐾",
      steps: [
        { text: "Tu mascota aparece flotando en la esquina derecha de la pantalla", illustration: "mascot" },
        { text: "Haz clic en ella para interactuar — salta y te da monedas", illustration: "mascot" },
        { text: "Habla con ella escribiendo mensajes en el chat", illustration: "mascot" },
        { text: "Haz clic en la moneda 🪙 para abrir la tienda de accesorios", illustration: "coins" },
        { text: "Compra accesorios con tus monedas acumuladas", illustration: "coins" },
        { text: "Los accesorios dan bonificaciones reales (más monedas, descuentos)", illustration: "coins" },
        { text: "Desbloquea mascotas premium completando logros", illustration: "ranking" },
      ],
      tip: "Explora la tienda todos los días para acumular más monedas.",
      url: "/",
      urlLabel: "Ir a la tienda",
    },
    {
      id: "monedas",
      title: "Ganar y usar monedas",
      icon: "🪙",
      steps: [
        { text: "🪙 Ganas monedas al interactuar con tu mascota (clics)", illustration: "mascot" },
        { text: "🪙 Ganas monedas al navegar y explorar productos", illustration: "scroll" },
        { text: "🪙 Ganas monedas al hacer compras", illustration: "cart" },
        { text: "🪙 Ganas monedas al completar tu perfil", illustration: "profile" },
        { text: "Usa monedas en la tienda de accesorios de mascotas", illustration: "coins" },
        { text: "Los accesorios desbloquean beneficios reales", illustration: "coins" },
      ],
      tip: "Las monedas no caducan — guardalas para accesorios premium.",
      url: "/",
      urlLabel: "Ir a la tienda",
    },
  ],
  ofertas: [
    {
      id: "ver-ofertas",
      title: "Cómo ver ofertas",
      icon: "🔥",
      steps: [
        { text: "Haz clic en '🔥 Ofertas' en el menú de navegación", illustration: "offers" },
        { text: "Verás todos los productos en descuento", illustration: "offers" },
        { text: "Filtra por categoría o precio", illustration: "categories" },
        { text: "Haz clic en el producto para ver el precio original y el descuento", illustration: "productCard" },
        { text: "Agrega al carrito y disfruta el descuento", illustration: "cart" },
      ],
      tip: "Las ofertas se actualizan cada lunes — ¡visítalas regularmente!",
      url: "/ofertas",
      urlLabel: "Ver ofertas",
    },
    {
      id: "usar-cupon",
      title: "Usar un cupón de descuento",
      icon: "🎫",
      steps: [
        { text: "Agrega productos al carrito", illustration: "cart" },
        { text: "Ve al checkout", illustration: "checkout" },
        { text: "Busca el campo 'Código de cupón'", illustration: "checkout" },
        { text: "Escribe o pega el código del cupón", illustration: "checkout" },
        { text: "Haz clic en 'Aplicar'", illustration: "checkout" },
        { text: "Verás el descuento reflejado en el total", illustration: "offers" },
        { text: "Confirma tu compra con el precio descontado", illustration: "notifications" },
      ],
      tip: "Los cupones de la ruleta son de un solo uso y caducan en 7 días.",
      url: "/spin-wheel",
      urlLabel: "Girar ruleta",
    },
    {
      id: "girar-ruleta",
      title: "Girar la ruleta de premios",
      icon: "🎰",
      steps: [
        { text: "Ve a la página de la ruleta de premios", illustration: "offers" },
        { text: "Haz clic en 'Girar'", illustration: "offers" },
        { text: "La ruleta girará y caerá en un premio", illustration: "offers" },
        { text: "Premios posibles: descuentos del 5%-50%, envío gratis, etc.", illustration: "offers" },
        { text: "El código del premio aparecerá en pantalla", illustration: "offers" },
        { text: "Usa el código en el checkout para aplicar el descuento", illustration: "checkout" },
      ],
      tip: "Puedes girar una vez cada 24 horas.",
      url: "/spin-wheel",
      urlLabel: "Ir a la ruleta",
    },
  ],
  envios: [
    {
      id: "politica-envios",
      title: "Política de envíos",
      icon: "📦",
      steps: [
        { text: "El vendedor coordina el envío después de confirmar el pago", illustration: "orders" },
        { text: "Transportistas disponibles: Servientrega, Olva, Shalom, etc.", illustration: "orders" },
        { text: "El costo de envío depende del peso y destino", illustration: "orders" },
        { text: "Recibirás un número de guía para rastrear tu paquete", illustration: "orders" },
        { text: "El tiempo de entrega es de 1 a 5 días hábiles", illustration: "orders" },
        { text: "Para Lima: entrega en 1-2 días. Provincias: 3-5 días", illustration: "orders" },
      ],
      tip: "Algunos vendedores ofrecen envío gratis en compras mayores.",
      url: "/",
      urlLabel: "Ver productos",
    },
  ],
};
