export const TUTORIAL_CATEGORIES = [
  {
    id: "compras",
    label: "Compras",
    icon: "🛒",
    description: "Cómo comprar productos",
    color: "from-green-400 to-emerald-500",
  },
  {
    id: "ventas",
    label: "Ventas",
    icon: "🏪",
    description: "Cómo vender en la plataforma",
    color: "from-blue-400 to-cyan-500",
  },
  {
    id: "pagos",
    label: "Pagos",
    icon: "💳",
    description: "Métodos de pago disponibles",
    color: "from-purple-400 to-violet-500",
  },
  {
    id: "dashboard",
    label: "Dashboard",
    icon: "📊",
    description: "Panel de control del vendedor",
    color: "from-orange-400 to-amber-500",
  },
  {
    id: "cuenta",
    label: "Mi Cuenta",
    icon: "👤",
    description: "Configuración y perfil",
    color: "from-pink-400 to-rose-500",
  },
  {
    id: "mascotas",
    label: "Mascotas",
    icon: "🐾",
    description: "Sistema de mascotas y monedas",
    color: "from-yellow-400 to-amber-500",
  },
  {
    id: "ofertas",
    label: "Ofertas",
    icon: "🔥",
    description: "Descuentos y promociones",
    color: "from-red-400 to-orange-500",
  },
  {
    id: "envios",
    label: "Envíos",
    icon: "📦",
    description: "Logística y entrega",
    color: "from-teal-400 to-cyan-500",
  },
];

export const TUTORIALS = {
  compras: [
    {
      id: "comprar-pasos",
      title: "Cómo comprar un producto",
      icon: "🛒",
      steps: [
        { text: "Busca el producto que deseas en la barra de búsqueda o explora las categorías" },
        { text: "Haz clic en el producto para ver detalles, fotos, precio y descripción" },
        { text: "Haz clic en 'Agregar al carrito' o 'Comprar ahora'" },
        { text: "Revisa tu carrito (ícono 🛒 arriba a la derecha)" },
        { text: "Haz clic en 'Ir al checkout' para confirmar tu compra" },
        { text: "Elige tu método de pago: Yape, Plin, transferencia bancaria o tarjeta" },
        { text: "Confirma el pedido y ¡listo! Recibirás un correo de confirmación" },
      ],
      tip: "Puedes agregar productos de diferentes tiendas en un solo pedido.",
      url: "/",
      urlLabel: "Ir a la tienda",
    },
    {
      id: "agregar-carrito",
      title: "Agregar productos al carrito",
      icon: "🛒",
      steps: [
        { text: "Encuentra el producto que te gusta" },
        { text: "Haz clic en 'Ver detalle' para abrir la página del producto" },
        { text: "Selecciona la cantidad que deseas" },
        { text: "Haz clic en el botón 'Agregar al carrito'" },
        { text: "El producto se añadirá a tu carrito (verás el contador incrementarse)" },
        { text: "Puedes seguir comprando o ir al carrito" },
      ],
      tip: "El carrito guarda tus productos aunque cierres el navegador.",
      url: "/",
      urlLabel: "Ver productos",
    },
    {
      id: "checkout-pago",
      title: "Proceso de pago (Checkout)",
      icon: "💳",
      steps: [
        { text: "Ve a tu carrito y haz clic en 'Ir al checkout'" },
        { text: "Revisa los productos y el total a pagar" },
        { text: "Ingresa tu dirección de envío" },
        { text: "Selecciona el método de pago preferido" },
        { text: "Si eliges Yape/Plin: envía el comprobante al vendedor" },
        { text: "Si eliges transferencia: realiza el depósito y sube el comprobante" },
        { text: "Si eliges tarjeta: ingresa los datos de tu tarjeta de forma segura" },
        { text: "Confirma el pedido — ¡recibirás un email de confirmación!" },
      ],
      tip: "Los pagos con Yape se confirman en minutos.",
      url: "/",
      urlLabel: "Ver productos",
    },
    {
      id: "seguir-pedido",
      title: "Seguir mi pedido",
      icon: "📦",
      steps: [
        { text: "Inicia sesión en tu cuenta" },
        { text: "Ve a 'Mi cuenta' → 'Mis pedidos'" },
        { text: "Selecciona el pedido que quieres rastrear" },
        { text: "Verás el estado actual: Pendiente / Procesando / Enviado / Entregado" },
        { text: "Si está enviado, verás el número de guía y transportista" },
        { text: "Haz clic en 'Seguimiento' para ver la ubicación en tiempo real" },
      ],
      tip: "También recibirás actualizaciones por email y WhatsApp.",
      url: "/",
      urlLabel: "Ir a mi cuenta",
    },
  ],
  ventas: [
    {
      id: "crear-tienda",
      title: "Crear mi tienda",
      icon: "🏪",
      steps: [
        { text: "Regístrate gratuitamente con tu email" },
        { text: "Inicia sesión en tu cuenta" },
        { text: "Ve a tu Dashboard (menú usuario → Dashboard)" },
        { text: "Haz clic en 'Configurar mi tienda'" },
        { text: "Ingresa el nombre de tu tienda" },
        { text: "Escribe una descripción atractiva" },
        { text: "Sube tu logo y banner" },
        { text: "¡Tu tienda está lista para vender!" },
      ],
      tip: "Las tiendas con logo y descripción completa venden 3 veces más.",
      url: "/dashboard",
      urlLabel: "Ir al Dashboard",
    },
    {
      id: "agregar-producto",
      title: "Agregar un producto",
      icon: "📦",
      steps: [
        { text: "Ve a Dashboard → Productos" },
        { text: "Haz clic en 'Nuevo Producto'" },
        { text: "Sube las fotos del producto (arrastra o selecciona)" },
        { text: "Escribe el nombre del producto (claro y descriptivo)" },
        { text: "Describe el producto con detalles: materiales, tamaño, uso" },
        { text: "Ingresa el precio en soles (S/)" },
        { text: "Selecciona la categoría" },
        { text: "Agrega stock disponible" },
        { text: "Haz clic en 'Guardar' — ¡tu producto está publicado!" },
      ],
      tip: "Usa fotos con fondo blanco y buena iluminación para mejor presentación.",
      url: "/dashboard/products",
      urlLabel: "Mis productos",
    },
    {
      id: "gestionar-pedidos",
      title: "Gestionar pedidos",
      icon: "🧾",
      steps: [
        { text: "Ve a Dashboard → Órdenes" },
        { text: "Verás todos los pedidos recibidos con su estado" },
        { text: "Haz clic en un pedido para ver detalles" },
        { text: "Cambia el estado según el progreso:" },
        { text: "  • Pendiente → Procesando (cuando empieces a preparar)" },
        { text: "  • Procesando → Enviado (cuando lo envíes)" },
        { text: "  • Enviado → Entregado (cuando el cliente reciba)" },
        { text: "Confirma el pago recibido del cliente" },
      ],
      tip: "Responde rápido a los clientes para mejorar tu reputación y ventas.",
      url: "/dashboard/orders",
      urlLabel: "Ver órdenes",
    },
    {
      id: "estadisticas",
      title: "Ver mis estadísticas",
      icon: "📊",
      steps: [
        { text: "Ve a Dashboard → Inicio" },
        { text: "En la parte superior verás las métricas principales:" },
        { text: "  • Productos publicados" },
        { text: "  • Pedidos totales" },
        { text: "  • Ingresos acumulados" },
        { text: "  • Visitas a tu tienda" },
        { text: "Desplázate hacia abajo para ver gráficos de tendencia" },
        { text: "Filtra por período: 7 días, 30 días, último trimestre" },
      ],
      tip: "Revisa tus estadísticas semanalmente para identificar productos más vendidos.",
      url: "/dashboard",
      urlLabel: "Ver Dashboard",
    },
  ],
  pagos: [
    {
      id: "metodos-pago",
      title: "Métodos de pago disponibles",
      icon: "💳",
      steps: [
        { text: "🟣 Yape — Pago instantáneo por celular. Solo envía el comprobante al vendedor." },
        { text: "🔵 Plin — Transferencia rápida entre bancos. Se confirma en minutos." },
        { text: "🏦 Transferencia bancaria — CCI o cuenta directa (BCP, Interbank, etc.)" },
        { text: "💳 Tarjeta de crédito/débito — Vía Culqi (100% seguro y encriptado)" },
        { text: "💵 PagoEfectivo — Paga en efectivo en tiendas autorizadas" },
      ],
      tip: "Yape y Plin son los métodos más rápidos para confirmar tu pedido.",
      url: "/",
      urlLabel: "Ir a comprar",
    },
    {
      id: "pagar-con-yape",
      title: "Pagar con Yape",
      icon: "📱",
      steps: [
        { text: "Selecciona Yape como método de pago en el checkout" },
        { text: "Copia el número de celular del vendedor (aparece en pantalla)" },
        { text: "Abre tu app Yape en tu celular" },
        { text: "Envía el monto exacto al número indicado" },
        { text: "Toma captura de pantalla del comprobante" },
        { text: "Sube la captura en el formulario de confirmación" },
        { text: "Haz clic en 'Confirmar pago' — ¡listo!" },
      ],
      tip: "El pago se confirma automáticamente en pocos minutos.",
      url: "/",
      urlLabel: "Ir a comprar",
    },
  ],
  dashboard: [
    {
      id: "panel-control",
      title: "Panel de control (Dashboard)",
      icon: "📊",
      steps: [
        { text: "Haz clic en tu avatar → 'Dashboard'" },
        { text: "Verás las tarjetas de acceso rápido:" },
        { text: "  • 📦 Productos — Gestionar tu catálogo" },
        { text: "  • 🧾 Órdenes — Ver y gestionar pedidos" },
        { text: "  • 📊 Estadísticas — Métricas de ventas" },
        { text: "  • ⚙️ Configurar — Ajustes de tu tienda" },
        { text: "Haz clic en cualquier tarjeta para acceder" },
      ],
      tip: "El dashboard se adapta a tu plan (Free o Full).",
      url: "/dashboard",
      urlLabel: "Abrir Dashboard",
    },
    {
      id: "configurar-tienda",
      title: "Configurar mi tienda",
      icon: "⚙️",
      steps: [
        { text: "Ve a Dashboard → Configurar" },
        { text: "Edita el nombre de tu tienda" },
        { text: "Escribe una descripción atractiva para tus clientes" },
        { text: "Sube tu logo (cuadrado, mínimo 200x200px)" },
        { text: "Sube un banner para la cabecera de tu tienda" },
        { text: "Configura tus datos de contacto" },
        { text: "Guarda los cambios — ¡tu tienda se actualiza al instante!" },
      ],
      tip: "Un logo profesional genera confianza en los compradores.",
      url: "/dashboard",
      urlLabel: "Configurar tienda",
    },
  ],
  cuenta: [
    {
      id: "editar-perfil",
      title: "Editar mi perfil",
      icon: "👤",
      steps: [
        { text: "Haz clic en tu avatar → 'Mi cuenta'" },
        { text: "Haz clic en 'Editar perfil'" },
        { text: "Actualiza tu nombre completo" },
        { text: "Agrega o cambia tu número de teléfono" },
        { text: "Sube una foto de perfil" },
        { text: "Guarda los cambios" },
      ],
      tip: "Un perfil completo genera más confianza en los compradores.",
      url: "/dashboard/profile/edit",
      urlLabel: "Editar perfil",
    },
    {
      id: "cambiar-contrasena",
      title: "Cambiar contraseña",
      icon: "🔒",
      steps: [
        { text: "Ve a Mi cuenta → Configuración" },
        { text: "Haz clic en 'Seguridad'" },
        { text: "Ingresa tu contraseña actual" },
        { text: "Escribe la nueva contraseña (mínimo 6 caracteres)" },
        { text: "Confirma la nueva contraseña" },
        { text: "Haz clic en 'Guardar'" },
      ],
      tip: "Usa una contraseña segura con letras, números y símbolos.",
      url: "/dashboard/profile/edit",
      urlLabel: "Configurar cuenta",
    },
    {
      id: "plan-full",
      title: "Actualizar a Plan Full",
      icon: "⬆️",
      steps: [
        { text: "Ve a Dashboard → Planes o haz clic en 'Upgrade'" },
        { text: "Revisa las ventajas del Plan Full:" },
        { text: "  • Vender sin límites de productos" },
        { text: "  • Herramientas de análisis avanzadas" },
        { text: "  • Soporte prioritario" },
        { text: "  • Mayor visibilidad en búsquedas" },
        { text: "Elige método de pago: Yape, transferencia o tarjeta" },
        { text: "Realiza el pago de S/ 199/año" },
        { text: "¡Tu cuenta se actualiza automáticamente!" },
      ],
      tip: "El Plan Full cuesta solo S/ 199/año (S/ 16.58/mes).",
      url: "/upgrade",
      urlLabel: "Ver Planes",
    },
  ],
  mascotas: [
    {
      id: "mascota-basico",
      title: "Cómo usar tu mascota",
      icon: "🐾",
      steps: [
        { text: "Tu mascota aparece flotando en la esquina derecha de la pantalla" },
        { text: "Haz clic en ella para interactuar — salta y te da monedas" },
        { text: "Habla con ella escribiendo mensajes en el chat" },
        { text: "Haz clic en la moneda 🪙 para abrir la tienda de accesorios" },
        { text: "Compra accesorios con tus monedas acumuladas" },
        { text: "Los accesorios dan bonificaciones reales (más monedas, descuentos)" },
        { text: "Desbloquea mascotas premium completando logros" },
      ],
      tip: "Explora la tienda todos los días para acumular más monedas.",
      url: "/",
      urlLabel: "Ir a la tienda",
    },
    {
      id: "monedas",
      title: "Ganar y usar monedas",
      icon: "🪙",
      steps: [
        { text: "🪙 Ganas monedas al interactuar con tu mascota (clics)" },
        { text: "🪙 Ganas monedas al navegar y explorar productos" },
        { text: "🪙 Ganas monedas al hacer compras" },
        { text: "🪙 Ganas monedas al completar tu perfil" },
        { text: "Usa monedas en la tienda de accesorios de mascotas" },
        { text: "Los accesorios desbloquean beneficios reales" },
      ],
      tip: "Las monedas no caducan — guardalas para accesorios premium.",
      url: "/",
      urlLabel: "Ir a la tienda",
    },
  ],
  ofertas: [
    {
      id: "ver-ofertas",
      title: "Cómo ver ofertas",
      icon: "🔥",
      steps: [
        { text: "Haz clic en '🔥 Ofertas' en el menú de navegación" },
        { text: "Verás todos los productos en descuento" },
        { text: "Filtra por categoría o precio" },
        { text: "Haz clic en el producto para ver el precio original y el descuento" },
        { text: "Agrega al carrito y disfruta el descuento" },
      ],
      tip: "Las ofertas se actualizan cada lunes — ¡visítalas regularmente!",
      url: "/ofertas",
      urlLabel: "Ver ofertas",
    },
    {
      id: "usar-cupon",
      title: "Usar un cupón de descuento",
      icon: "🎫",
      steps: [
        { text: "Agrega productos al carrito" },
        { text: "Ve al checkout" },
        { text: "Busca el campo 'Código de cupón'" },
        { text: "Escribe o pega el código del cupón" },
        { text: "Haz clic en 'Aplicar'" },
        { text: "Verás el descuento reflejado en el total" },
        { text: "Confirma tu compra con el precio descontado" },
      ],
      tip: "Los cupones de la ruleta son de un solo uso y caducan en 7 días.",
      url: "/spin-wheel",
      urlLabel: "Girar ruleta",
    },
    {
      id: "girar-ruleta",
      title: "Girar la ruleta de premios",
      icon: "🎰",
      steps: [
        { text: "Ve a la página de la ruleta de premios" },
        { text: "Haz clic en 'Girar'" },
        { text: "La ruleta girará y caerá en un premio" },
        { text: "Premios posibles: descuentos del 5%-50%, envío gratis, etc." },
        { text: "El código del premio aparecerá en pantalla" },
        { text: "Usa el código en el checkout para aplicar el descuento" },
      ],
      tip: "Puedes girar una vez cada 24 horas.",
      url: "/spin-wheel",
      urlLabel: "Ir a la ruleta",
    },
  ],
  envios: [
    {
      id: "politica-envios",
      title: "Política de envíos",
      icon: "📦",
      steps: [
        { text: "El vendedor coordina el envío después de confirmar el pago" },
        { text: "Transportistas disponibles: Servientrega, Olva, Shalom, etc." },
        { text: "El costo de envío depende del peso y destino" },
        { text: "Recibirás un número de guía para rastrear tu paquete" },
        { text: "El tiempo de entrega es de 1 a 5 días hábiles" },
        { text: "Para Lima: entrega en 1-2 días. Provincias: 3-5 días" },
      ],
      tip: "Algunos vendedores ofrecen envío gratis en compras mayores.",
      url: "/",
      urlLabel: "Ver productos",
    },
  ],
};
