export const MASCOTS = {
  box: {
    id: "box",
    name: "Cajita",
    description: "Una caja de cartón con cara simpática. Tu compañero fiel desde el inicio.",
    type: "default",
    unlockCondition: null,
    unlockLabel: "Disponible para todos",
    color: "#F59E0B",
    emoji: "📦",
  },
  coin: {
    id: "coin",
    name: "Monedita",
    description: "Una moneda sonriente que brilla con luz propia. Celebra tus compras.",
    type: "default",
    unlockCondition: null,
    unlockLabel: "Disponible para todos",
    color: "#EAB308",
    emoji: "🪙",
  },
  cart: {
    id: "cart",
    name: "Carrito",
    description: "Un carrito de compras con brazos y mucha energía. ¡Listo para cargar!",
    type: "default",
    unlockCondition: null,
    unlockLabel: "Disponible para todos",
    color: "#22C55E",
    emoji: "🛒",
  },
  coupon: {
    id: "coupon",
    name: "Cupón",
    description: "Un cupón con ojos y sombrero de copa. Siempre tiene un descuento.",
    type: "default",
    unlockCondition: null,
    unlockLabel: "Disponible para todos",
    color: "#A855F7",
    emoji: "🎟️",
  },
  bag: {
    id: "bag",
    name: "Bolsa",
    description: "Una bolsa de compras elegante. Para los que saben lo que quieren.",
    type: "default",
    unlockCondition: null,
    unlockLabel: "Disponible para todos",
    color: "#EC4899",
    emoji: "🛍️",
  },
  box_c: {
    id: "box_c",
    name: "Cajita Violeta",
    description: "Una caja de cartón violeta con cara de sueño. ¡Siempre tranquila!",
    type: "premium",
    unlockCondition: "first_purchase",
    unlockLabel: "Realiza tu primera compra",
    color: "#8B5CF6",
    emoji: "📦",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
  coin_a: {
    id: "coin_a",
    name: "Moneda Dorada",
    description: "Una moneda dorada con águila. ¡Brilla con luz propia!",
    type: "premium",
    unlockCondition: "3_purchases",
    unlockLabel: "Realiza 3 compras",
    color: "#F59E0B",
    emoji: "🪙",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
  cart_a: {
    id: "cart_a",
    name: "Carrito Azul",
    description: "Un carrito de compras azul, listo para cargar todo.",
    type: "premium",
    unlockCondition: "first_sale",
    unlockLabel: "Realiza tu primera venta",
    color: "#3B82F6",
    emoji: "🛒",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
  cart_b: {
    id: "cart_b",
    name: "Carrito Rojo",
    description: "Un carrito de compras rojo con mucha energía.",
    type: "premium",
    unlockCondition: "5_products",
    unlockLabel: "Publica 5 productos",
    color: "#EF4444",
    emoji: "🛒",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
  coupon_c: {
    id: "coupon_c",
    name: "Cupón Verde",
    description: "Un cupón verde con 'GRATIS'. ¡Siempre tiene un descuento!",
    type: "premium",
    unlockCondition: "5_reviews",
    unlockLabel: "Escribe 5 reseñas",
    color: "#22C55E",
    emoji: "🎟️",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
  bag_b: {
    id: "bag_b",
    name: "Bolsa Preocupada",
    description: "Una bolsa de papel con cara de preocupación. ¡Pero todo bien!",
    type: "premium",
    unlockCondition: "spend_200",
    unlockLabel: "Gasta S/ 200 en total",
    color: "#D97706",
    emoji: "🛍️",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
  rocket_b: {
    id: "rocket_b",
    name: "Cohete Rojo",
    description: "Un cohete rojo que va rápido. ¡Entregas express!",
    type: "premium",
    unlockCondition: "10_products_sold",
    unlockLabel: "Vende 10 productos",
    color: "#DC2626",
    emoji: "🚀",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
  dog_c: {
    id: "dog_c",
    name: "Perrito Dorado",
    description: "Un perrito dorado con sueño. ¡El compañero más fiel!",
    type: "premium",
    unlockCondition: "10_products_sold",
    unlockLabel: "Vende 10 productos",
    color: "#EAB308",
    emoji: "🐕",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
  cat_b: {
    id: "cat_b",
    name: "Gatito Gris",
    description: "Un gatito gris con rayas. ¡Elegante y juguetón!",
    type: "premium",
    unlockCondition: "spend_500",
    unlockLabel: "Gasta S/ 500 en total",
    color: "#6B7280",
    emoji: "🐱",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
  chicken_b: {
    id: "chicken_b",
    name: "Pollito Blanco",
    description: "Un pollito blanco con cresta roja. ¡Siempre alegre!",
    type: "premium",
    unlockCondition: "top_seller",
    unlockLabel: "Alcanza 50 ventas",
    color: "#F97316",
    emoji: "🐔",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
  rooster_b: {
    id: "rooster_b",
    name: "Gallito Amarillo",
    description: "Un pollito amarillo con cresta roja. ¡Energía pura!",
    type: "premium",
    unlockCondition: "mega_seller",
    unlockLabel: "Alcanza 100 ventas",
    color: "#F59E0B",
    emoji: "🐤",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
  cuy_c: {
    id: "cuy_c",
    name: "Cuy",
    description: "Un cuy marrón con cara tierna. ¡El mascot más lindo!",
    type: "premium",
    unlockCondition: "mega_seller",
    unlockLabel: "Alcanza 100 ventas",
    color: "#92400E",
    emoji: "🐹",
    hasImages: true,
    views: { front: null, side: null, rear: null },
  },
};

export const MASCOT_LIST = Object.values(MASCOTS);
export const DEFAULT_MASCOT = "box";

export const ACHIEVEMENT_DEFINITIONS = {
  first_purchase: {
    type: "first_purchase",
    title: "Primera Compra",
    description: "Realizaste tu primera compra en la tienda",
    mascotReward: "box_c",
    icon: "🎉",
  },
  "3_purchases": {
    type: "3_purchases",
    title: "Comprador Frecuente",
    description: "Realizaste 3 compras",
    mascotReward: "coin_a",
    icon: "🛒",
  },
  first_sale: {
    type: "first_sale",
    title: "Primera Venta",
    description: "Realizaste tu primera venta",
    mascotReward: "cart_a",
    icon: "💰",
  },
  "5_products": {
    type: "5_products",
    title: "Catálogo Crece",
    description: "Publicaste 5 productos",
    mascotReward: "cart_b",
    icon: "📦",
  },
  "5_reviews": {
    type: "5_reviews",
    title: "Crítico Constructivo",
    description: "Escribiste 5 reseñas",
    mascotReward: "coupon_c",
    icon: "⭐",
  },
  spend_200: {
    type: "spend_200",
    title: "Buen Comprador",
    description: "Gastaste S/ 200 en total",
    mascotReward: "bag_b",
    icon: "💰",
  },
  "10_products_sold": {
    type: "10_products_sold",
    title: "Vendedor Activo",
    description: "Vendiste 10 productos",
    mascotReward: "rocket_b",
    icon: "🏆",
  },
  spend_500: {
    type: "spend_500",
    title: "Gran Comprador",
    description: "Gastaste S/ 500 en total",
    mascotReward: "cat_b",
    icon: "💰",
  },
  top_seller: {
    type: "top_seller",
    title: "Top Seller",
    description: "Alcanzaste 50 ventas",
    mascotReward: "chicken_b",
    icon: "🏆",
  },
  mega_seller: {
    type: "mega_seller",
    title: "Leyenda de Ventas",
    description: "Alcanzaste 100 ventas",
    mascotReward: "cuy_c",
    icon: "👑",
  },
};

export function getMascotById(id) {
  return MASCOTS[id] || MASCOTS[DEFAULT_MASCOT];
}

export function getUnlockedMascots(achievements, userRole) {
  if (userRole?.toLowerCase() === "admin") {
    return MASCOT_LIST.map((m) => m.id);
  }
  const unlockedIds = MASCOT_LIST.filter((m) => m.type === "default").map((m) => m.id);
  achievements.forEach((a) => {
    const def = ACHIEVEMENT_DEFINITIONS[a.type];
    if (def?.mascotReward) {
      unlockedIds.push(def.mascotReward);
    }
  });
  return [...new Set(unlockedIds)];
}
